server:
  port: 8443
  tomcat:
    uri-encoding: UTF-8

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: Tuni_back

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:9988/tuni
    username: root
    password: 1234

  servlet:
    multipart:
      enabled: true
      location: C:/upload/temp
      max-file-size: 40MB
      max-request-size: 20MB
      file-size-threshold: 100MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ssc114321@gmail.com
    password: sffqcfcvopgicdkj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.project.tuni_back.domain  
  configuration:
    map-underscore-to-camel-case: true
jwt:
  secret: MIICWwIBAAKBgQCeWA0pmOn2vHF+xYvluMyd0GcivmKjN/rFgdRHiWEg7t/1M7k7
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 604800
